import { NgModule, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { RouterModule } from '@angular/router';
import { JhiTrackerService } from './../shared/tracker/tracker.service';

import { ArtonexpressSharedModule } from '../shared';
/* jhipster-needle-add-admin-module-import - JHipster will add admin modules imports here */

import {
    adminState,
    AuditsComponent,
    UserMgmtComponent,
    UserDialogComponent,
    UserDeleteDialogComponent,
    UserMgmtDetailComponent,
    UserMgmtDialogComponent,
    UserMgmtDeleteDialogComponent,
    LogsComponent,
    JhiMetricsMonitoringModalComponent,
    JhiMetricsMonitoringComponent,
    JhiHealthModalComponent,
    JhiHealthCheckComponent,
    JhiConfigurationComponent,
    JhiDocsComponent,
    AuditsService,
    JhiConfigurationService,
    JhiHealthService,
    JhiMetricsService,
    JhiTrackerComponent,
    LogsService,
    UserResolvePagingParams,
    UserResolve,
    UserModalService,
    AdminAddressComponent,
    AdminAddressDeleteDialogComponent,
    AdminAddressDeletePopupComponent,
    AdminAddressDetailComponent,
    AdminAddressDialogComponent,
    AdminAddressPopupComponent,
    AdminAddressResolvePagingParams,
    AdminItemComponent,
    AdminItemDeleteDialogComponent,
    AdminItemDeletePopupComponent,
    AdminItemDetailComponent,
    AdminItemDialogComponent,
    AdminItemPopupComponent,
    AdminItemResolvePagingParams,
    AdminLabelComponent,
    AdminLabelDeleteDialogComponent,
    AdminLabelDeletePopupComponent,
    AdminLabelDetailComponent,
    AdminLabelDialogComponent,
    AdminLabelPopupComponent,
    AdminLabelResolvePagingParams,
    AdminOrderComponent,
    AdminOrderDeleteDialogComponent,
    AdminOrderDeletePopupComponent,
    AdminOrderDetailComponent,
    AdminOrderDialogComponent,
    AdminOrderPopupComponent,
    AdminOrderResolvePagingParams,
    AdminPromotionComponent,
    AdminPromotionDeleteDialogComponent,
    AdminPromotionDeletePopupComponent,
    AdminPromotionDetailComponent,
    AdminPromotionDialogComponent,
    AdminPromotionPopupComponent,
    AdminPromotionResolvePagingParams,
    AdminReceiptComponent,
    AdminReceiptDeleteDialogComponent,
    AdminReceiptDeletePopupComponent,
    AdminReceiptDetailComponent,
    AdminReceiptDialogComponent,
    AdminReceiptPopupComponent,
    AdminReceiptResolvePagingParams,
    AdminServiceComponent,
    AdminServiceDeleteDialogComponent,
    AdminServiceDeletePopupComponent,
    AdminServiceDetailComponent,
    AdminServiceDialogComponent,
    AdminServicePopupComponent,
    AdminServiceResolvePagingParams,
    PasswordService,
    PasswordStrengthBarComponent,
    PasswordComponent,
    SettingsComponent,
    AdminAccountPopupComponent,
} from './';
import {AdminComponent} from './admin.component';
import {MdButtonModule, MdCardModule, MdMenuModule} from '@angular/material';
import {SearchFilterPipe} from "../pipes/filter.pipe";
import {AdminAccountComponent} from "./account/admin-account.component";
import {AdminAccountDialogComponent} from "./account/admin-account-dialog.component";
import {PromotionService} from "../entities/promotion/promotion.service";

@NgModule({
    imports: [
        ArtonexpressSharedModule,
        RouterModule.forRoot(adminState, { useHash: true }),
        /* jhipster-needle-add-admin-module - JHipster will add admin modules here */
        MdButtonModule,
        MdCardModule,
        MdMenuModule
    ],
    declarations: [
        AuditsComponent,
        UserMgmtComponent,
        UserDialogComponent,
        UserDeleteDialogComponent,
        UserMgmtDetailComponent,
        UserMgmtDialogComponent,
        UserMgmtDeleteDialogComponent,
        LogsComponent,
        JhiConfigurationComponent,
        JhiHealthCheckComponent,
        JhiHealthModalComponent,
        JhiDocsComponent,
        JhiTrackerComponent,
        JhiMetricsMonitoringComponent,
        JhiMetricsMonitoringModalComponent,
        AdminComponent,
        AdminAddressComponent,
        AdminAddressDeleteDialogComponent,
        AdminAddressDeletePopupComponent,
        AdminAddressDetailComponent,
        AdminAddressDialogComponent,
        AdminAddressPopupComponent,
        AdminItemComponent,
        AdminItemDeleteDialogComponent,
        AdminItemDeletePopupComponent,
        AdminItemDetailComponent,
        AdminItemDialogComponent,
        AdminItemPopupComponent,
        AdminLabelComponent,
        AdminLabelDeleteDialogComponent,
        AdminLabelDeletePopupComponent,
        AdminLabelDetailComponent,
        AdminLabelDialogComponent,
        AdminLabelPopupComponent,
        AdminOrderComponent,
        AdminOrderDeleteDialogComponent,
        AdminOrderDeletePopupComponent,
        AdminOrderDetailComponent,
        AdminOrderDialogComponent,
        AdminOrderPopupComponent,
        AdminPromotionComponent,
        AdminPromotionDeleteDialogComponent,
        AdminPromotionDeletePopupComponent,
        AdminPromotionDetailComponent,
        AdminPromotionDialogComponent,
        AdminPromotionPopupComponent,
        AdminReceiptComponent,
        AdminReceiptDeleteDialogComponent,
        AdminReceiptDeletePopupComponent,
        AdminReceiptDetailComponent,
        AdminReceiptDialogComponent,
        AdminReceiptPopupComponent,
        AdminServiceComponent,
        AdminServiceDeleteDialogComponent,
        AdminServiceDeletePopupComponent,
        AdminServiceDetailComponent,
        AdminServiceDialogComponent,
        AdminServicePopupComponent,
        PasswordComponent,
        PasswordStrengthBarComponent,
        SettingsComponent,
        SearchFilterPipe,
        AdminAccountComponent,
        AdminAccountPopupComponent,
        AdminAccountDialogComponent
    ],
    entryComponents: [
        UserMgmtDialogComponent,
        UserMgmtDeleteDialogComponent,
        JhiHealthModalComponent,
        JhiMetricsMonitoringModalComponent,
        AdminAddressDeleteDialogComponent,
        AdminAddressDialogComponent,
        AdminItemDeleteDialogComponent,
        AdminItemDialogComponent,
        AdminLabelDeleteDialogComponent,
        AdminLabelDialogComponent,
        AdminOrderDeleteDialogComponent,
        AdminOrderDialogComponent,
        AdminPromotionDeleteDialogComponent,
        AdminPromotionDialogComponent,
        AdminReceiptDeleteDialogComponent,
        AdminReceiptDialogComponent,
        AdminServiceDeleteDialogComponent,
        AdminServiceDialogComponent,
        AdminAccountDialogComponent
    ],
    providers: [
        AuditsService,
        JhiConfigurationService,
        JhiHealthService,
        JhiMetricsService,
        LogsService,
        JhiTrackerService,
        UserResolvePagingParams,
        UserResolve,
        UserModalService,
        AdminAddressResolvePagingParams,
        AdminItemResolvePagingParams,
        AdminLabelResolvePagingParams,
        AdminOrderResolvePagingParams,
        AdminPromotionResolvePagingParams,
        AdminReceiptResolvePagingParams,
        AdminServiceResolvePagingParams,
        PasswordService,
        PromotionService
    ],
    schemas: [CUSTOM_ELEMENTS_SCHEMA]
})
export class ArtonexpressAdminModule {}
